version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3005:443"
    environment:
      - VITE_BACK_URL=backend:3006
    networks:
      - prescription
    restart: on-failure
  backend:
    build: ./backend
    ports:
      - "3006:3006"
    environment:
      DB_HOST: db
    networks:
      - postgres_network
      - prescription
    restart: on-failure
    volumes:
      - backendLogs:/app/logs/
  db:
    image: postgres
    networks:
      - postgres_network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prescription
    restart: on-failure
    volumes:
      - dbData:/var/lib/postgresql/data

volumes:
  dbData:
  backendLogs:

networks:
  prescription: {}
  postgres_network: {}
