version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3005:80"
    environment:
      - VITE_BACK_URL=backend:3006
    networks:
      - prescription
  backend:
    build: ./backend
    ports:
      - "3006:5000"
    environment:
      - DB_HOST=db
    networks:
      - postgres_network
      - prescription
    restart: on-failure
  db:
    image: postgres
    networks:
      - postgres_network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prescription
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:

networks:
  prescription: {}
  postgres_network: {}
